// Mocks generated by Mockito 5.0.11 from annotations
// in qrtestcodeone/test/mock.dart.
// Do not manually edit this file.

import 'dart:async' as _i5;

import 'package:mockito/mockito.dart' as _i1;
import 'package:qrtestcodeone/data/model/qr_seed_datamodel.dart' as _i3;
import 'package:qrtestcodeone/domain/entity/qr_seed.dart' as _i2;

import 'mock.dart' as _i4;

// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: comment_references
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis

class _FakeQrSeed extends _i1.Fake implements _i2.QrSeed {}

class _FakeQrSeedDataModel extends _i1.Fake implements _i3.QrSeedDataModel {}

class _FakeDateTime extends _i1.Fake implements DateTime {
  @override
  String toString() => super.toString();
}

/// A class which mocks [MockQrCodeRepository].
///
/// See the documentation for Mockito's code generation for more information.
class MockMockQrCodeRepository extends _i1.Mock
    implements _i4.MockQrCodeRepository {
  MockMockQrCodeRepository() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i5.Future<_i2.QrSeed> getSeed() =>
      (super.noSuchMethod(Invocation.method(#getSeed, []),
              returnValue: Future<_i2.QrSeed>.value(_FakeQrSeed()))
          as _i5.Future<_i2.QrSeed>);
  @override
  String toString() => super.toString();
}

/// A class which mocks [MockQrCodeServiceDataSource].
///
/// See the documentation for Mockito's code generation for more information.
class MockMockQrCodeServiceDataSource extends _i1.Mock
    implements _i4.MockQrCodeServiceDataSource {
  MockMockQrCodeServiceDataSource() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i5.Future<_i3.QrSeedDataModel> getSeed() =>
      (super.noSuchMethod(Invocation.method(#getSeed, []),
              returnValue:
                  Future<_i3.QrSeedDataModel>.value(_FakeQrSeedDataModel()))
          as _i5.Future<_i3.QrSeedDataModel>);
  @override
  String toString() => super.toString();
}

/// A class which mocks [QrSeedDataModel].
///
/// See the documentation for Mockito's code generation for more information.
class MockQrSeedDataModel extends _i1.Mock implements _i3.QrSeedDataModel {
  @override
  String get seed =>
      (super.noSuchMethod(Invocation.getter(#seed), returnValue: '') as String);
  @override
  DateTime get expiresAt => (super.noSuchMethod(Invocation.getter(#expiresAt),
      returnValue: _FakeDateTime()) as DateTime);
  @override
  List<Object?> get props =>
      (super.noSuchMethod(Invocation.getter(#props), returnValue: <Object?>[])
          as List<Object?>);
  @override
  _i2.QrSeed toQrSeed() => (super.noSuchMethod(Invocation.method(#toQrSeed, []),
      returnValue: _FakeQrSeed()) as _i2.QrSeed);
  @override
  Map<String, dynamic> toJson() =>
      (super.noSuchMethod(Invocation.method(#toJson, []),
          returnValue: <String, dynamic>{}) as Map<String, dynamic>);
  @override
  String toString() => super.toString();
}
