// Mocks generated by Mockito 5.0.16 from annotations
// in seed_reader/test/mocks/mock_generator.dart.
// Do not manually edit this file.

import 'dart:async' as _i4;

import 'package:mockito/mockito.dart' as _i1;
import 'package:seed_reader/interactors/seed_interactor.dart' as _i3;
import 'package:seed_reader/models/seed.dart' as _i2;

// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types

class _FakeSeed_0 extends _i1.Fake implements _i2.Seed {}

/// A class which mocks [SeedInteractor].
///
/// See the documentation for Mockito's code generation for more information.
class MockSeedInteractor extends _i1.Mock implements _i3.SeedInteractor {
  MockSeedInteractor() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i4.Future<_i2.Seed> fetchSeed() =>
      (super.noSuchMethod(Invocation.method(#fetchSeed, []),
              returnValue: Future<_i2.Seed>.value(_FakeSeed_0()))
          as _i4.Future<_i2.Seed>);
  @override
  bool isValid(_i2.Seed? seed) => (super
          .noSuchMethod(Invocation.method(#isValid, [seed]), returnValue: false)
      as bool);
  @override
  String toString() => super.toString();
}
