// Mocks generated by Mockito 5.0.15 from annotations
// in qr_generator/test/domain/qr_generator/mocks/mocker.dart.
// Do not manually edit this file.

import 'dart:async' as _i4;

import 'package:dartz/dartz.dart' as _i2;
import 'package:mockito/mockito.dart' as _i1;
import 'package:qr_generator/domain/model/failure.dart' as _i5;
import 'package:qr_generator/domain/model/qr_code.dart' as _i6;
import 'package:qr_generator/domain/qr_generator/repository/qr_generator_repo.dart'
    as _i3;

// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis

class _FakeEither_0<L, R> extends _i1.Fake implements _i2.Either<L, R> {}

/// A class which mocks [QRGeneratorRepository].
///
/// See the documentation for Mockito's code generation for more information.
class MockQRGeneratorRepository extends _i1.Mock
    implements _i3.QRGeneratorRepository {
  MockQRGeneratorRepository() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i4.Future<_i2.Either<_i5.Failure, _i6.QRCode>> generateQRCode() =>
      (super.noSuchMethod(Invocation.method(#generateQRCode, []),
              returnValue: Future<_i2.Either<_i5.Failure, _i6.QRCode>>.value(
                  _FakeEither_0<_i5.Failure, _i6.QRCode>()))
          as _i4.Future<_i2.Either<_i5.Failure, _i6.QRCode>>);
  @override
  String toString() => super.toString();
}
