include: package:lint/analysis_options.yaml

analyzer:
  errors:
    missing_required_param: error
    missing_return: error
    must_be_immutable: error
    sort_unnamed_constructors_first: ignore
    avoid_print: ignore
    avoid_function_literals_in_foreach_calls: ignore
    must_call_super: error
    invalid_use_of_protected_member: error
    parameter_assignments: error
    sort_pub_dependencies: ignore
  exclude:
    - "**/*.g.dart"
    - "**/*.gr.dart"
    - "**/*.freezed.dart"
    - "**/injection.config.dart"