name: flutter_qr_lib
description: Flutter library for displaying a QR code from seed data.
version: 0.0.1
author: Scott Cornell
homepage: https://github.com/scornell10/mobile-test

environment:
    sdk: '>=2.7.0 <3.0.0'
    flutter: '>=1.20.0'

dependencies:
    flutter:
        sdk: flutter

dev_dependencies:
    flutter_test:
        sdk: flutter

flutter:
    plugin:
        platforms:
            android:
                package: com.sdc.flutter_qr_lib
                pluginClass: FlutterQrLibPlugin
            ios:
                pluginClass: FlutterQrLibPlugin
