name: super_qr
description: Superformula would like to display a QR code that identifies one's profile or feature.

version: 0.0.1+1

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  qr_flutter: ^2.1.0
  cloud_firestore: ^0.12.6

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
