name: qr_generator
description: >
  A simple app that can call the seed API and generate a QR code based on the
  seed.

publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=2.10.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  qr_code_gen:
    git:
      url: git://github.com/marcossevilla/qr_code_gen

  cupertino_icons: ^1.0.0
  flutter_riverpod: ^0.12.4
  freezed_annotation: ^0.12.0
  i18n_extension: ^2.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  build_runner:
  freezed: ^0.12.7
  mockito: ^4.1.4
  very_good_analysis: ^1.0.4

flutter:
  uses-material-design: true
