import 'dart:convert';
import 'package:dio/dio.dart';
import 'package:flutter/material.dart';
import 'package:qr_code_test/blocs/qrfetch/qrfetch.dart';

/// An HTTP repository that returns a [Seed] object generated by an HTTP server.
class HttpQRRepository extends QRRepository {
  /// Creates a new repository that fetches QR from an HTTP server
  const HttpQRRepository();

  @override
  Future<Seed> getData({@required Dio dio}) async {
    // Making the HTTP request
    final response = await dio.get<String>("/seed");

    // Converting from json
    final decoded = jsonDecode(response.data) as Map<String, dynamic>;

    // Returning the actual instance
    return Seed.fromJson(decoded);
  }
}