import 'dart:convert';
import 'package:http/http.dart' as http;
import 'package:qr_code_test/blocs/qrfetch/qrfetch.dart';
import 'package:qr_code_test/configs/configurations.dart';

/// An HTTP repository that returns a [Seed] object generated by an HTTP server.
class HttpQRRepository extends QRRepository {
  /// Creates a new repository that fetches QR from an HTTP server
  const HttpQRRepository();

  @override
  Future<Seed> getData() async {
    // Making the HTTP request
    final response = await http.get(Configurations.baseHttpEndpointAndroid + "/seed");

    // Converting from json
    final decoded = jsonDecode(response.body) as Map<String, dynamic>;

    // Returning the actual instance
    return Seed.fromJson(decoded);
  }
}