name: qr_api
description: A Very Good Project created by Very Good CLI.
version: 1.0.0+1
publish_to: none

environment:
  sdk: ">=2.13.0 <3.0.0"

dependencies:
  dio: ^4.0.0
  freezed: ^0.14.5
  freezed_annotation: ^0.14.3
  qr_models:
    path: ../qr_models

dev_dependencies:
  build_runner: ^2.0.0
  test: ^1.17.0
  very_good_analysis: ^2.3.0