source 'https://github.com/CocoaPods/Specs.git'

platform :ios, '12.0'
use_frameworks!

def shared_pods
    pod 'Alamofire', '~> 4.7'
end

target 'QRSample'  do

  # Pods for QRSample
  shared_pods

  target 'QRSampleTests' do
    inherit! :search_paths
    # Pods for testing
    shared_pods
    pod 'OHHTTPStubs/Swift'
  end

  target 'QRSampleUITests' do
    inherit! :search_paths
    # Pods for UI testing
  end
end

post_install do |installer|
  installer.pods_project.targets.each do |target|
    puts target.name
  end
end
