name: qr_app
description: Displays QR code from seed data and scans QR code images.

publish_to: 'none'

version: 1.0.0+1

environment:
    sdk: '>=2.7.0 <3.0.0'

dependencies:
    flutter:
        sdk: flutter

    flutter_qr_lib:
        path: ../flutter_qr_lib

    cupertino_icons: ^1.0.0
    get_it: ^5.0.6
    provider: ^4.3.3
    rxdart: ^0.25.0
    http: ^0.12.2
    qr_code_scanner: ^0.3.2
    flutter_config: ^1.0.8

dev_dependencies:
    flutter_test:
        sdk: flutter
    mockito: ^4.1.4

flutter:
    uses-material-design: true
