// Mocks generated by Mockito 5.0.15 from annotations
// in qr_generator/test/data/qr_generator/mocks/mocker.dart.
// Do not manually edit this file.

import 'dart:async' as _i4;

import 'package:http/http.dart' as _i2;
import 'package:mockito/mockito.dart' as _i1;
import 'package:qr_generator/data/api/api.dart' as _i3;

// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis

class _FakeResponse_0 extends _i1.Fake implements _i2.Response {}

/// A class which mocks [QRApi].
///
/// See the documentation for Mockito's code generation for more information.
class MockQRApi extends _i1.Mock implements _i3.QRApi {
  MockQRApi() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i4.Future<_i2.Response> generateQR() =>
      (super.noSuchMethod(Invocation.method(#generateQR, []),
              returnValue: Future<_i2.Response>.value(_FakeResponse_0()))
          as _i4.Future<_i2.Response>);
  @override
  String toString() => super.toString();
}
