name: seed_server
description: A simple command-line application.
# version: 1.0.0
# homepage: https://www.example.com
#Fernanda Silva Dias - fernandasd26@gmail.com
environment:
  sdk: '>=2.10.0 <3.0.0'

dev_dependencies:
  pedantic: ^1.9.0
