name: qr_generator_api
description: A Dart API Client for the QR Generator API
version: 0.1.0+1
publish_to: none

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  equatable: ^2.0.5
  http: ^1.0.0
  json_annotation: ^4.8.1

dev_dependencies:
  build_runner: ^2.0.5
  json_serializable: ^6.7.0
  mocktail: ^0.3.0
  test: ^1.19.2
  very_good_analysis: ^3.1.0
  
