name: qr_gen
description: Dart package to manage qr_gen data and domain layers.
version: 0.0.1+1

publish_to: "none"

environment:
  sdk: ">=2.10.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  errors:
    git:
      url: git://github.com/NoScopeDevs/errors

  network_manager:
    git:
      url: git://github.com/NoScopeDevs/network_manager

  qr_code_gen:
    git:
      url: git://github.com/marcossevilla/qr_code_gen

  dartz: ^0.9.2
  equatable: ^1.2.6
  json_annotation: ^4.0.0
  meta: ^1.3.0
  path: ^1.8.0

dev_dependencies:
  # Code generation
  build_runner: ^1.11.5
  json_serializable: ^4.0.1

  # Testing
  mockito: ^4.1.4
  test: ^1.16.3

  # Static analysis
  very_good_analysis: ^1.0.4
