name: qr_generator_flutter
description: A new Flutter project.

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  #* State Management
  flutter_bloc: ^6.1.2

  #* Dependency Injection
  get_it: ^6.0.0

  cupertino_icons: ^1.0.0
  freezed_annotation: ^0.12.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  freezed: ^0.12.7
  build_runner: ^1.11.5
  mockito: ^4.1.4
  bloc_test: ^7.1.0

flutter:
  uses-material-design: true
